### ISSUE TITLE
Correct for unintended junction at bridges/tunnels

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/NetworkModel_EU#10]
voor arc2segment,

dit is alleen een echt junction, als ze allebei dezlfde junction_ID hebben vogels TomTom

idea:
z_var = 0 als maaiveld, 1 als brug/tunnel

Wat als er meer dan 2 lagen heeft?

**Comment by jipclaassens** [comment]
Maarten just commented that we might not need arc2segments anymore since we corrected the network for the 'wrong' node identifiers. Since we omitted the two-way-arcs.

**Comment by cjacobscrisioni** [comment]
Arc2segments may still be necessary to connect the O/D points?

My idea here is to expand the nodeset into a 3-dimensional feature, in which the z-value takes the F_Node and T_Node relations. To do so it is crucial that, after dropping the return-loop from the geometries, the f_nodes and t_nodes (from Junctions) correspond with the first_node and last_node of the cleaned geometry.

I did extensive checks today, and can confirm that in 99.99% of cases these do represent the same location (according to a spatial comparison of the upoints of the frompoint, topoint, and associated junction geometry). Notes:
- table-based comparisons seemed to show identical coordinates, but comparisons on exact locations yielded zero results
- point_IsNearby(frompoint, junction geom, 1d) also yielded zero results surprisingly

**Comment by cjacobscrisioni** [comment]
Converted the code so that the initial network now adopts the Tom Tom junctions. The network efficiency steps should follow in cascade. Waiting for PC capacity to regenerate the EU networks. Stepwise checks still necessary:

- [ ] No overlap in /CreateInitialWorkingNetwork/LinkSet_Calc/location_connectors/F1 and (...)F2
- [ ] And no overlap between the prior and CreateInitialWorkingNetwork/LinkSet_Calc/unchanged_links/F1 and (...) F2
- [ ] Check for nulls in /NetworkSetup/Base_Analysis/NetwerkSpec/CreateInitialWorkingNetwork/LinkSet_Calc/changed_links/F1 and (....) F2
- [ ] Check for no subnetworks in the final /NetworkSetup/Base_Analysis/NetwerkSpec/CreateInitialWorkingNetwork/LinkSet
- [ ] Check if the steps in the network efficiency improver do not introduce relations between links and nodes based on location only.

**Comment by cjacobscrisioni** [comment]
Checking in process... The F2s (ie cutpoints) in  /CreateInitialWorkingNetwork/LinkSet_Calc/location_connectors/ need to be adjusted, so that they are grouped together into one node whenever multiple location_connectors share the same physical cutpoint location

**Comment by cjacobscrisioni** [comment]
/CreateInitialWorkingNetwork/LinkSet_Calc/location_connectors/F2 does need to overlap, as cutpoints may have snapped on connectable pre-existing nodes without a physical link change.

**Comment by cjacobscrisioni** [comment]
Fixed snags in CreateInitialWorkingNetwork, network seems to be functionally reproducing TomTom connectivity rules now for instance where the Amsterdamsebrug spans the Westelijke Merwedekanaaldijk

**Comment by jipclaassens** [comment]
@MaartenHilferink ter info
